#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CSS="$ROOT_DIR/artifacts/themes/omarchy-darktable.css"
SCREENSHOT="$ROOT_DIR/artifacts/screenshots/omarchy-darktable-demo.svg"
FIXTURE="$ROOT_DIR/tests/fixtures/omarchy-fixture-colors.toml"

fail() {
  echo "check failed: $*" >&2
  exit 1
}

require_file() {
  [ -f "$1" ] || fail "missing file $1"
}

require_text() {
  local file="$1"
  local pattern="$2"
  rg -q -- "$pattern" "$file" || fail "missing pattern '$pattern' in $file"
}

require_failure_text() {
  local pattern="$1"
  shift
  local output
  if output="$("$@" 2>&1)"; then
    fail "expected command to fail: $*"
  fi
  printf '%s' "$output" | rg -q -- "$pattern" || fail "expected failure matching '$pattern' from: $*"
}

require_failure_text "Invalid DARKTABLE_THEME_NAME" env \
  SOURCE="$CSS" \
  DARKTABLE_THEME_NAME="../escaped.css" \
  "$ROOT_DIR/scripts/install-theme.sh"
require_failure_text "Refusing to install outside" env \
  DARKTABLE_THEME_DIR="$HOME/.config/darktable/themes/.." \
  DARKTABLE_THEME_NAME="escaped.css" \
  SOURCE="$CSS" \
  "$ROOT_DIR/scripts/install-theme.sh"
require_failure_text "Invalid DARKTABLE_THEME_NAME" env \
  DARKTABLE_THEME_NAME="../escaped.css" \
  "$ROOT_DIR/scripts/rollback.sh"
require_failure_text "Refusing to remove outside" env \
  DARKTABLE_THEME_DIR="$HOME/.config/darktable/themes/.." \
  DARKTABLE_THEME_NAME="escaped.css" \
  "$ROOT_DIR/scripts/rollback.sh"

"$ROOT_DIR/scripts/generate-theme.sh" --colors "$FIXTURE" --out "$CSS" >/dev/null
"$ROOT_DIR/scripts/export-demo.sh" >/dev/null

require_file "$CSS"
require_file "$SCREENSHOT"
require_file "$ROOT_DIR/demo/index.html"
require_file "$ROOT_DIR/docs/native-mapping.md"
require_file "$ROOT_DIR/docs/color-critical-surfaces.md"
require_file "$ROOT_DIR/docs/screenshot-workflow.md"

require_text "$CSS" "Generated by Omarchy Native Kit for darktable"
require_text "$CSS" "Downstream Omarchy Native Kit Darktable integration layer"
require_text "$CSS" "@define-color omarchy_accent #7aa2f7;"
require_text "$CSS" "@define-color omarchy_photo_canvas #262626;"
require_text "$CSS" "dt_omarchy_shadow"
require_text "$CSS" "#left, #right, #top, #bottom"
require_text "$CSS" "\\.dt_module"
require_text "$CSS" "\\.dt_bauhaus"
require_text "$CSS" "#bauhaus-slider"
require_text "$CSS" "button:focus"
require_text "$CSS" "scrollbar slider"
require_text "$CSS" "tooltip"
require_text "$CSS" "popover"
require_text "$CSS" "dialog"
require_text "$CSS" "treeview\\.view"
require_text "$CSS" "#center, #preview, #thumbtable"
require_text "$CSS" "#histogram"
require_text "$CSS" "\\.dt_warning"
require_text "$CSS" "\\.dt_error"
require_text "$CSS" "\\.dt_success"
require_text "$CSS" "\\.dt_info"

require_text "$ROOT_DIR/scripts/install-theme.sh" '\$HOME/.config/darktable/themes'
require_text "$ROOT_DIR/scripts/install-theme.sh" "Refusing to overwrite non-generated theme"
require_text "$ROOT_DIR/scripts/install-theme.sh" "Invalid DARKTABLE_THEME_NAME"
require_text "$ROOT_DIR/scripts/rollback.sh" "Downstream Omarchy Native Kit Darktable integration layer"
require_text "$ROOT_DIR/scripts/rollback.sh" "Invalid DARKTABLE_THEME_NAME"
require_text "$ROOT_DIR/README.md" "rollback"
require_text "$ROOT_DIR/docs/screenshot-workflow.md" "./scripts/capture-darktable.sh"
require_text "$ROOT_DIR/scripts/capture-darktable.sh" "--conf ui_last/theme=omarchy"
require_text "$SCREENSHOT" "neutral review canvas"

echo "All checks passed."
